#!/usr/bin/python
# a tiny script for padding a numerical column in a csv with 0s
# worth using argparse if extended

import pandas as pd
import sys

df = pd.read_csv(sys.stdin, dtype=object)

df[sys.argv[1]] = df[sys.argv[1]].apply(lambda x: x.zfill(int(sys.argv[2])))

df.to_csv(sys.stdout, index=False)

