#! /usr/bin/python

"""
renames csv files on the command line

loads whole csv file into memory,
so obviously very inefficient
"""

import pandas as pd
import sys

df = pd.read_csv(sys.stdin, dtype=object)

parts = sys.argv[1:]

args = {x.split(':')[0].strip(): x.split(':')[1].strip() for x in parts}

df.rename(columns=args, inplace=True)
df.to_csv(sys.stdout, index=False)
